name: Main CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
        preset:
        - default
        - devel
    env:
      VCPKG_ROOT: /usr/local/share/vcpkg

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cmake -B build --preset=${{ matrix.preset }} -DBUILD_TESTS=ON
          cmake --build build -j"$(nproc)"

      - name: Test
        run: |
          ctest -V --test-dir build/

      - name: Lint
        run: |
          sudo apt-get update
          sudo apt-get install -y bear

          bear -- make -C memory-management/

          find ./ -type f -name '*.cpp' -print0 -o -name '*.h' -print0 |
            xargs -0 clang-tidy -p build/compile_commands.json --config-file=.clang-tidy --warnings-as-errors='*'

  format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Formatting check
        run: |
          find ./ -type f -name '*.cpp' -print0 -o -name '*.h' -print0 |
            xargs -0 clang-format -Werror --style=file -n
