name: Main CI
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
        preset:
        - default
        - devel
    env:
      VCPKG_ROOT: /usr/local/share/vcpkg
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
      - uses: actions/checkout@v4

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Build
        run: |
          cmake -B build --preset=${{ matrix.preset }} -DBUILD_TESTS=ON
          cmake --build build -j"$(nproc)"

      - name: Test
        run: |
          ctest -V --test-dir build/

      - name: Lint
        run: |
          find ./ -type f -name '*.cpp' -print0 -o -name '*.h' -print0 |
            xargs -0 clang-tidy -p build/compile_commands.json --config-file=.clang-tidy --warnings-as-errors='*'

  format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Formatting check
        run: |
          find ./ -type f -name '*.cpp' -print0 -o -name '*.h' -print0 |
            xargs -0 clang-format -Werror --style=file -n
